apiVersion: v1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.releaseName }}-statefulset
  labels:
    app: {{ .Values.kafka.releaseName }}-app
spec:
  serviceName: {{ .Values.kafka.releaseName }}-service
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.releaseName }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.releaseName }}-app
    spec:
      containers:
        - name: {{ .Values.kafka.releaseName }}-container
          image: {{ .Values.kafka.image.name }}:{{ .Values.kafka.image.tag }}
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
            - name: broker
              containerPort: {{ .Values.kafka.service.controllerPort }}
            - name: controller
              containerPort: {{ .Values.kafka.service.controllerTargetPort }}
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_PROCESS_ROLES
              value: {{ .Values.kafka.configuration.KAFKA_PROCESS_ROLES }}
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: {{ .Values.kafka.configuration.KAFKA_CONTROLLER_QUORUM_VOTERS }}
            - name: KAFKA_LISTENERS
              value: {{ .Values.kafka.configuration.KAFKA_LISTENERS }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.configuration.LISTENER_SECURITY_PROTOCOL_MAP }}
            - name: CLUSTER_NAME
              value: "{{ .Values.kafka.clusterName }}"
            - name: KAFKA_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.kafka.releaseName }}-config
                  key: CLUSTER_ID
          command:
            - sh
            - -c
            - |
              # Extract numeric index from pod name (e.g., kafka-0 -> 0)
              export KAFKA_NODE_ID=$(echo $KAFKA_NODE_ID | awk -F'-' '{print $NF}')
              # Generate advertised listeners dynamically per pod
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://kafka-${KAFKA_NODE_ID}.kafka-svc.default.svc.cluster.local:9092"
              exec /etc/confluent/docker/run
    volumeClaimTemplates:
      - metadata:
          name: kafka-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi      