global:
  application:
    name: uber
  database:
    postgres:
      DB_HOST: uber-db-postgresql.uber-ns-app.svc.cluster.local
      DB_PORT: 5432
      DB_NAME: ride_hailing_db
      DB_USER: zannujulius
      DB_PASSWORD: uber_password
  jwt:
    JWT_SECRET: "eating!!@223upTwich21ggS"
    JWT_REFRESH_SECRET: "refresh!!@223upTwich21ggS"
  namespace:
    name: uber-ns-app
  maps:
    GOOGLE_MAPS_API_KEY: "AIzaSyC8V6tQNc5t-wQb5DUnr1mOwhQ5qcGu7jI"
  github:
    GIT_USERNAME: zannujulius
